README.org --- description



Copyright (C) 2010 Roman V. Prikhodchenko



Author: Roman V. Prikhodchenko <chujoii@gmail.com>



  This file is part of bldc-esc.

  bldc-esc is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  bldc-esc is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with bldc-esc.  If not, see <http://www.gnu.org/licenses/>.



* Keywords:
  electronic speed control esc brushless dc electric motor bldc electronically commutated motors 

* Description:
  electronic speed control for brushless dc electric motor (schematic + program for microcontroller + example program for test)

* Usage:

* History:
  Project started at 2010.01(Jan).03






* Dependences:
  
  
